stages: 
  - buildx
  - build

prepare-buildx: 
  artifacts: 
    expire_in: "48 hours"
    paths: 
      - buildx
  image: "docker:19.03"
#  image: "${REGISTRY_PROJECT}/hocker:buildhelper_buildx"
  services: 
    - "docker:19.03-dind"
  stage: buildx
  script:
    - echo "::PREP:BUILDX:"
    - apk add git bash
    - export DOCKER_BUILDKIT=1
    - git clone git://github.com/docker/buildx ./docker-buildx
    - docker build --platform=local -o . ./docker-buildx
#  script: 
#    - echo "::PREP:BUILDX:"
#    - apk add git bash
#    - /bin/bash -c "uname -a ;uptime;pwd;ls"
#    - "/bin/bash _build.hocker.sh buildx"

  variables: 
    GIT_SUBMODULE_STRATEGY: recursive

before_script: 
  - uptime
  #- "docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST} || true"

hocker-builder-latest: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:19.03"
  only: 
    - master
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh latest"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
hocker-builder-p5: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:19.03"
  only: 
    - master
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh php5"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
hocker-builder-p7: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:19.03"
  only: 
    - master
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh php7"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive

hocker-builder-aux: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:19.03"
  only: 
    - master
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh aux"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive

