stages: 
  - buildx
  - build

prepare-buildx: 
  artifacts: 
    expire_in: "1 hour"
    paths: 
      - buildx
  image: "docker:latest"
  script: 
    - "apk add git bash"
    - "export DOCKER_BUILDKIT=1"
    - "git clone git://github.com/docker/buildx ./docker-buildx"
    - "docker build --platform=local -o . ./docker-buildx"
    - "docker pull  ${REGISTRY_PROJECT}/hocker:buildhelper_buildx"
    - "docker build --platform=local -t ${REGISTRY_PROJECT}/hocker:buildhelper_buildx -o . ./docker-buildx"
    - "echo -n \":REG_LOGIN:\""
    - "docker login  -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}"
    - "echo -n \":DOCKER:PUSH@\"${REGISTRY_PROJECT}/hocker:buildhelper_buildx\":\""
    - "docker push ${REGISTRY_PROJECT}/hocker:buildhelper_buildx"
  services: 
    - "docker:19.03-dind"
  stage: buildx
  variables: 
    GIT_STRATEGY: none


before_script: 
  - uptime
  - "docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST} || true"

hocker-builder-latest: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:stable"
  only: 
    - master
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh latest"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
hocker-builder-p5: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:stable"
  only: 
    - master
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh php5"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
hocker-builder-p7: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:stable"
  only: 
    - master
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh php7"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive

hocker-builder-aux: 
  artifacts: 
    paths: 
      - buildlogs
    when: always
  before_script: ~
  image: "docker:stable"
  only: 
    - master
  script: 
    - uptime
    - "apk add git bash"
    - "/bin/bash _build.hocker.sh aux"
  services: 
    - 
      command: 
        - "--experimental"
      name: "docker:19.03-dind"
  stage: build
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
